version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: project/vue-js-example:latest
    # The app will restart until Mongo is listening
    restart: always
    ports:
      - "8081:8081"
    stdin_open: true  # -i
    tty: true         # -t

